
package org.webservice.service.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 *
 */
@WebService(name = "AuthorService", targetNamespace = "http://services.service.WebService.org/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface AuthorService {


    /**
     *
     * @param arg0
     * @return
     *     returns org.webservice.service.services.Author
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuthorByBooktitle", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.GetAuthorByBooktitle")
    @ResponseWrapper(localName = "getAuthorByBooktitleResponse", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.GetAuthorByBooktitleResponse")
    @Action(input = "http://services.service.WebService.org/AuthorService/getAuthorByBooktitleRequest", output = "http://services.service.WebService.org/AuthorService/getAuthorByBooktitleResponse")
    public Author getAuthorByBooktitle(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     *
     * @param arg0
     * @return
     *     returns java.util.List<org.webservice.service.services.Author>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuthorByName", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.GetAuthorByName")
    @ResponseWrapper(localName = "getAuthorByNameResponse", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.GetAuthorByNameResponse")
    @Action(input = "http://services.service.WebService.org/AuthorService/getAuthorByNameRequest", output = "http://services.service.WebService.org/AuthorService/getAuthorByNameResponse")
    public List<Author> getAuthorByName(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     *
     * @return
     *     returns java.util.List<org.webservice.service.services.Author>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAuthors", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.ListAuthors")
    @ResponseWrapper(localName = "listAuthorsResponse", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.ListAuthorsResponse")
    @Action(input = "http://services.service.WebService.org/AuthorService/listAuthorsRequest", output = "http://services.service.WebService.org/AuthorService/listAuthorsResponse")
    public List<Author> listAuthors();

    /**
     *
     * @param arg0
     * @return
     *     returns org.webservice.service.services.Author
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuthorById", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.GetAuthorById")
    @ResponseWrapper(localName = "getAuthorByIdResponse", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.GetAuthorByIdResponse")
    @Action(input = "http://services.service.WebService.org/AuthorService/getAuthorByIdRequest", output = "http://services.service.WebService.org/AuthorService/getAuthorByIdResponse")
    public Author getAuthorById(
            @WebParam(name = "arg0", targetNamespace = "")
                    Integer arg0);

    /**
     *
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createAuthor", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.CreateAuthor")
    @ResponseWrapper(localName = "createAuthorResponse", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.CreateAuthorResponse")
    @Action(input = "http://services.service.WebService.org/AuthorService/createAuthorRequest", output = "http://services.service.WebService.org/AuthorService/createAuthorResponse")
    public void createAuthor(
            @WebParam(name = "arg0", targetNamespace = "")
                    Author arg0);

}