
package org.webservice.service.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EditorService", targetNamespace = "http://services.service.WebService.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EditorService {


    /**
     * 
     * @param arg0
     * @return
     *     returns org.webservice.service.services.Editor
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEditorByBookTitle", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.GetEditorByBookTitle")
    @ResponseWrapper(localName = "getEditorByBookTitleResponse", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.GetEditorByBookTitleResponse")
    @Action(input = "http://services.service.WebService.org/EditorService/getEditorByBookTitleRequest", output = "http://services.service.WebService.org/EditorService/getEditorByBookTitleResponse")
    public Editor getEditorByBookTitle(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.webservice.service.services.Editor>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEditorByName", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.GetEditorByName")
    @ResponseWrapper(localName = "getEditorByNameResponse", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.GetEditorByNameResponse")
    @Action(input = "http://services.service.WebService.org/EditorService/getEditorByNameRequest", output = "http://services.service.WebService.org/EditorService/getEditorByNameResponse")
    public List<Editor> getEditorByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<org.webservice.service.services.Editor>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listEditors", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.ListEditors")
    @ResponseWrapper(localName = "listEditorsResponse", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.ListEditorsResponse")
    @Action(input = "http://services.service.WebService.org/EditorService/listEditorsRequest", output = "http://services.service.WebService.org/EditorService/listEditorsResponse")
    public List<Editor> listEditors();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.webservice.service.services.Editor
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEditorById", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.GetEditorById")
    @ResponseWrapper(localName = "getEditorByIdResponse", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.GetEditorByIdResponse")
    @Action(input = "http://services.service.WebService.org/EditorService/getEditorByIdRequest", output = "http://services.service.WebService.org/EditorService/getEditorByIdResponse")
    public Editor getEditorById(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
