
package org.webservice.service.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://services.service.WebService.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.UpdateUserResponse")
    @Action(input = "http://services.service.WebService.org/UserService/updateUserRequest", output = "http://services.service.WebService.org/UserService/updateUserResponse")
    public void updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAccount arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.webservice.service.services.UserAccount
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUserByEmail", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.FindUserByEmail")
    @ResponseWrapper(localName = "findUserByEmailResponse", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.FindUserByEmailResponse")
    @Action(input = "http://services.service.WebService.org/UserService/findUserByEmailRequest", output = "http://services.service.WebService.org/UserService/findUserByEmailResponse")
    public UserAccount findUserByEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createUser", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.CreateUserResponse")
    @Action(input = "http://services.service.WebService.org/UserService/createUserRequest", output = "http://services.service.WebService.org/UserService/createUserResponse")
    public void createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAccount arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "validateLogin", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.ValidateLogin")
    @ResponseWrapper(localName = "validateLoginResponse", targetNamespace = "http://services.service.WebService.org/", className = "org.webservice.service.services.ValidateLoginResponse")
    @Action(input = "http://services.service.WebService.org/UserService/validateLoginRequest", output = "http://services.service.WebService.org/UserService/validateLoginResponse")
    public void validateLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        UserAccount arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
